# DATA
dataset : 'CULane'
data_root : ''
row_anchor : [121, 131, 141, 150, 160, 170, 180, 189, 199, 209, 219, 228, 238, 248, 258, 267, 277, 287]

# TRAIN
epoch : 50
batch_size : 32
optimizer : 'SGD'  #['SGD','Adam']
learning_rate : 0.1
weight_decay : 1e-4
momentum : 0.9

scheduler : 'multi' #['multi', 'cos']
steps : [25,38]
gamma  : 0.1
warmup : 'linear'
warmup_iters : 695

# NETWORK
use_aux : True
backbone : '18'
griding_num : 200

# LOSS
sim_loss_w : 0.0
shp_loss_w : 0.0

# EXP
note : ''

log_path : ''

# FINETUNE or RESUME MODEL PATH
finetune : ''
resume : ''

# TEST
test_model : ''
test_work_dir : ''

num_lanes : 4